import { describe, expect, it } from 'vitest';
import { NFL_TEAM_CODES_32 } from '../src/fixtures/teamWeekRawV0FullLeagueScaffold.js';
import {
  validateTeamWeekByeAwareCoverage,
  type TeamWeekCoverageRow
} from '../src/validation/teamWeekRawV0Coverage.js';

/** The real 2024 regular-season week window: Weeks 1-18 (no synthetic-scaffold weeks 1-6 here). */
const REGULAR_SEASON_WEEKS_2024 = Array.from({ length: 18 }, (_, i) => i + 1);
const EXPECTED_GAMES_PER_TEAM = 17;
const EXPECTED_TOTAL_ROWS = NFL_TEAM_CODES_32.length * EXPECTED_GAMES_PER_TEAM;

const byeWeekFor = (teamIndex: number): number => (teamIndex % REGULAR_SEASON_WEEKS_2024.length) + 1;

/**
 * Small, deterministic, generated bye-aware fixture: 32 teams x weeks 1-18, with exactly one bye
 * week per team staggered by team index, producing 17 game rows per team (544 total). This is a
 * shape/coverage fixture only (mirroring the dense-grid scaffold's neutral-placeholder approach) and
 * invents no real 2024 schedule or outcomes; it exists purely to exercise the validator.
 */
const buildByeAwareFixtureRows = (season = 2024): TeamWeekCoverageRow[] => {
  const rows: TeamWeekCoverageRow[] = [];
  NFL_TEAM_CODES_32.forEach((team_code, teamIndex) => {
    const byeWeek = byeWeekFor(teamIndex);
    for (const week of REGULAR_SEASON_WEEKS_2024) {
      if (week === byeWeek) continue;
      rows.push({ team_code, week, season });
    }
  });
  return rows;
};

const baseExpectation = {
  expectedTeams: NFL_TEAM_CODES_32,
  expectedWeeks: REGULAR_SEASON_WEEKS_2024,
  expectedGamesPerTeam: EXPECTED_GAMES_PER_TEAM,
  expectedSeason: 2024
};

describe('team_week_raw_v0 bye-aware coverage validator', () => {
  it('accepts a generated 32-team x 17-game shape over weeks 1-18 (544 rows)', () => {
    const rows = buildByeAwareFixtureRows();
    expect(rows).toHaveLength(EXPECTED_TOTAL_ROWS);
    expect(rows).toHaveLength(544);

    const result = validateTeamWeekByeAwareCoverage(rows, baseExpectation);

    expect(result.errors).toEqual([]);
    expect(result.valid).toBe(true);
    expect(result.isFullLeague).toBe(true);
    expect(result.teamCount).toBe(32);
    expect(result.totalRowCount).toBe(544);
  });

  it('does not require or synthesize a row for any team bye week', () => {
    const rows = buildByeAwareFixtureRows();
    const weeksByTeam = new Map<string, Set<number>>();
    for (const row of rows) {
      if (!weeksByTeam.has(row.team_code)) weeksByTeam.set(row.team_code, new Set());
      weeksByTeam.get(row.team_code)!.add(row.week);
    }

    NFL_TEAM_CODES_32.forEach((team, teamIndex) => {
      expect(weeksByTeam.get(team)!.has(byeWeekFor(teamIndex))).toBe(false);
      expect(weeksByTeam.get(team)!.size).toBe(EXPECTED_GAMES_PER_TEAM);
    });

    // The validator must accept this bye-shaped fixture as-is (no synthesized row added back).
    expect(validateTeamWeekByeAwareCoverage(rows, baseExpectation).valid).toBe(true);
  });

  it('fails if a team has only 16 rows (a second missing week beyond its bye)', () => {
    const rows = buildByeAwareFixtureRows();
    const secondMissingWeek = rows.find((r) => r.team_code === 'KC')!.week;
    const mutated = rows.filter((r) => !(r.team_code === 'KC' && r.week === secondMissingWeek));

    const result = validateTeamWeekByeAwareCoverage(mutated, baseExpectation);

    expect(result.valid).toBe(false);
    expect(result.isFullLeague).toBe(false);
    expect(
      result.errors.some((e) => e.includes('team "KC" has 16 game row(s), expected exactly 17'))
    ).toBe(true);
  });

  it('fails if a team has 18 rows (a row restored for its own bye week)', () => {
    const rows = buildByeAwareFixtureRows();
    const kcByeWeek = byeWeekFor(NFL_TEAM_CODES_32.indexOf('KC'));
    const mutated = [...rows, { team_code: 'KC', week: kcByeWeek, season: 2024 }];

    const result = validateTeamWeekByeAwareCoverage(mutated, baseExpectation);

    expect(result.valid).toBe(false);
    expect(result.isFullLeague).toBe(false);
    expect(
      result.errors.some((e) => e.includes('team "KC" has 18 game row(s), expected exactly 17'))
    ).toBe(true);
  });

  it('fails on a duplicate team-week row', () => {
    const rows = buildByeAwareFixtureRows();
    const mutated = [...rows, rows[0]!];

    const result = validateTeamWeekByeAwareCoverage(mutated, baseExpectation);

    expect(result.valid).toBe(false);
    expect(
      result.errors.some((e) =>
        e.includes(`duplicate row for team "${rows[0]!.team_code}" week ${rows[0]!.week}`)
      )
    ).toBe(true);
  });

  it('fails on an unexpected team code', () => {
    const rows = buildByeAwareFixtureRows();
    const mutated = [...rows, { team_code: 'XXX', week: 1, season: 2024 }];

    const result = validateTeamWeekByeAwareCoverage(mutated, baseExpectation);

    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.includes('unexpected team "XXX"'))).toBe(true);
  });

  it('fails on an out-of-window week (e.g. week 19), isolated from the row-count check', () => {
    const rows = buildByeAwareFixtureRows();
    const ariRows = rows.filter((r) => r.team_code === 'ARI');
    const otherRows = rows.filter((r) => r.team_code !== 'ARI');
    // Swap one ARI game week for an out-of-window week 19, keeping ARI's row count at 17 so this
    // exercises only the out-of-window check, not the "expected exactly 17" count check.
    const mutatedAriRows = [{ ...ariRows[0]!, week: 19 }, ...ariRows.slice(1)];
    const mutated = [...otherRows, ...mutatedAriRows];

    const result = validateTeamWeekByeAwareCoverage(mutated, baseExpectation);

    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.includes('team "ARI" has out-of-window week 19'))).toBe(true);
    expect(result.errors.some((e) => e.includes('expected exactly 17'))).toBe(false);
  });

  it('fails on a row from another season standing in for a missing expected-season row', () => {
    const rows = buildByeAwareFixtureRows(2024);
    // Drop one genuine 2024 row for KC and replace it with the same (team_code, week) sourced from
    // a different season. Team/week/count/duplicate/window checks all still pass on their own -
    // only the per-row season check should catch this.
    const kcRow = rows.find((r) => r.team_code === 'KC')!;
    const withoutKcRow = rows.filter((r) => !(r.team_code === 'KC' && r.week === kcRow.week));
    const mutated = [...withoutKcRow, { team_code: 'KC', week: kcRow.week, season: 2023 }];

    const result = validateTeamWeekByeAwareCoverage(mutated, baseExpectation);

    expect(result.valid).toBe(false);
    expect(result.isFullLeague).toBe(false);
    expect(
      result.errors.some((e) =>
        e.includes(`team "KC" week ${kcRow.week} has season 2023, expected season 2024`)
      )
    ).toBe(true);
    expect(result.errors.some((e) => e.includes('expected exactly 17'))).toBe(false);
    expect(result.errors.some((e) => e.includes('out-of-window'))).toBe(false);
  });
});
